### ISSUE TITLE
Menu Button placement issue with Skin Shuffle !

### ISSUE THREAD

**Issue by NayxYann** [zOnlyKroks/P2P#5]
Hello,

The menu button for P2P is not well placed to use alongside Skin Shuffle, they are crossing each others !

![image](https://github.com/zOnlyKroks/P2P/assets/117595486/4ea3dce5-0fce-4b09-bd5f-935aadfce336)

Maybe adding a button to disable it or move it to the Options menu could be a good idea.

Have a nice day.

**Comment by NayxYann** [comment]
Or maybe above the accessibility Settings button.

**Comment by zOnlyKroks** [comment]
i will take a look in a short while

**Comment by zOnlyKroks** [comment]
Update is pushed, this should now be fixed. i Close this now, if something similar comes up just make a new issue ;D
