### ISSUE TITLE
inconsistency? maybe??

### ISSUE THREAD

**Issue by carbage14** [zOnlyKroks/P2P#6]
when you join your singleplayer world and click p2p, it says "no world selected," when it should be the world name you just selected. just an inconsistency and doesn't really affect gameplay all that much but i just thought it was strange, and im nitpicky
![image_2024-06-12_233714339](https://github.com/zOnlyKroks/P2P/assets/172576427/bf6b927b-23dc-4575-988b-42ada6a442ab)

**Comment by zOnlyKroks** [comment]
First of all, nice to know that someone actually uses this mod. And I will take a look at this later today / tomorrow ;D

**Comment by zOnlyKroks** [comment]
> when you join your singleplayer world and click p2p, it says "no world selected," when it should be the world name you just selected. just an inconsistency and doesn't really affect gameplay all that much but i just thought it was strange, and im nitpicky ![image_2024-06-12_233714339](https://private-user-images.githubusercontent.com/172576427/339239909-bf6b927b-23dc-4575-988b-42ada6a442ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjEyNTEsIm5iZiI6MTcxODI2MDk1MSwicGF0aCI6Ii8xNzI1NzY0MjcvMzM5MjM5OTA5LWJmNmI5MjdiLTIzZGMtNDU3NS05ODhiLTQyYWRhNmE0NDJhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwNjQyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTVlYWRjNmU0YTE0MWIzNmExZDUwMTc0Njk4YTQ4NmRjNDI0NWNjZmYxNzQ0NTc0OWYyODYyMjRiZjJkNGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ydV39Fo63_hyWzlEaEh3UvSJvriA21Rse5rGSUbHduQ)

What version is this?

**Comment by carbage14** [comment]
1.20.6

**Comment by zOnlyKroks** [comment]
Should be fixed
