### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by chickenforday** [zOnlyKroks/P2P#9]
Would it be possible to put a config to enable offline mode?

**Comment by zOnlyKroks** [comment]
I dont really know what you want / how it would be possible. If you want LAN sharing Minecraft has it built in. As for offline mode in authentication against the minecraft server: No. I wont allow this mod to work in cracked scenarios

**Comment by zOnlyKroks** [comment]
I am closing this as this seems to be out of scope for this mod / ToS of Minecraft. Open again if you think this is wrong with more details.

**Comment by chickenforday** [comment]
Ohh okay thank you anyways
